# Site settings
title: "Pioneras Developers"
logo: logo.png # image from https://www.flickr.com/photos/lwr/5496279831/in/set-72157594159055823
email: pionerasdevelopers@gmail.com
description: > # this means to ignore newlines until "url:"
  Cuando un grupo de personas encuentra en gusto en común se convierten en un comunidad, eso somos nosotras
  una comunidad de mujeres unidas por el amor a la programación.
url: "http://pionerasdevelopers.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: pionerasdevelopers
github_username:  pionerasdevelopers

permalink: /:title
paginate: 5

# Build settings
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-paginate
